/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import gestortarjetas.Movimiento;
import gestortarjetas.TarjetaCredito;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Esta clase permite crear un JDialog con el que podremos realizar
 * transacciones y almacenarlas en nuestra base de datos.
 *
 * @author Heriberto Amezcua
 * @version 3.0
 * @since JDK 11.0.17
 */
public class JDPagar extends javax.swing.JDialog {

    private TarjetaCredito tarjeta;
    private Movimiento nuevoMovimiento;
    private boolean haPagado;

    /**
     * Creates new form JDPagar
     */
    public JDPagar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializar();
    }

    /**
     * Permite crear un JDialog con el que podremos realizar pagos con una
     * tarjeta de credito.
     *
     * @param parent
     * @param modal
     * @param t la tarjeta con la que queremos realizar una transaccion
     */
    public JDPagar(java.awt.Frame parent, boolean modal, TarjetaCredito t) {
        super(parent, modal);
        initComponents();
        inicializar();
        this.haPagado = false;
        this.tarjeta = t;
    }

    /**
     *
     * @return true si se ha realizado un pago correctamente
     */
    public boolean getHaPagado() {
        return this.haPagado;
    }

    /**
     *
     * @return el nuevo movimiento que se ha creado al pagar null si no se ha
     * realizado la transaccion
     */
    public Movimiento getNuevoMovimiento() {
        return new Movimiento(this.nuevoMovimiento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        labelTitulo = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelConcepto = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaConcepto = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTitulo.setText("Realizar Pago");

        labelCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCantidad.setText("Cantidad:");

        labelConcepto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelConcepto.setText("Concepto:");

        textAreaConcepto.setColumns(20);
        textAreaConcepto.setRows(5);
        jScrollPane1.setViewportView(textAreaConcepto);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPagar.setText("PAGAR");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelConcepto)
                            .addComponent(labelCantidad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTitulo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidad)
                    .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelConcepto)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * JButton que cierra el JDialog cuando hacemos click izquierdo sobre el.
     *
     * @param evt click izquierdo
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * JButton que cuando hacemos click izquierdo sobre el crea un objeto
     * movimiento asociado a la tarjeta de credito introducida en el JDialog o
     * da un mensaje de error si ha habido algun error.
     *
     * @param evt click izquierdo
     */
    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        String cantidad = textCantidad.getText(),
                concepto = textAreaConcepto.getText();

        if (esEntero(cantidad) || esDouble(cantidad)) {
            if (this.tarjeta.pagar(Double.parseDouble(cantidad), concepto, this.tarjeta)) {
                this.nuevoMovimiento = new Movimiento(Double.parseDouble(cantidad), concepto, this.tarjeta);
                this.haPagado = true;
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se ha podido realizar el pago. Concepto inválido o saldo superado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se ha podido realizar el pago. Cantidad inválida.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        this.setVisible(false);

    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * Permite comprobar si un string podria ser numerico double
     *
     * @param s el string a comprobar
     * @return true si todos los caracteres del string son digitos y separados
     * por un unico punto
     */
    private boolean esDouble(String s) {
        Pattern ptrDouble = Pattern.compile("^[-+]?\\d*\\.+\\d{1,2}$");
        Matcher matchDouble = ptrDouble.matcher(s);

        return matchDouble.matches();
    }

    /**
     * Permite comprobar si un string podria ser numerico entero
     *
     * @param s el string a comprobar
     * @return true si todos los caracteres del string a comprobar son digitos.
     */
    private static boolean esEntero(String s) {
        if (s == null || s.equals("")) {
            return false;
        }

        return s.chars().allMatch(Character::isDigit);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDPagar dialog = new JDPagar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelConcepto;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextArea textAreaConcepto;
    private javax.swing.JTextField textCantidad;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo que nos permite alterar el estado del JDialog cuando queramos
     * inicializarlo con estos valores.
     */
    private void inicializar() {
        setLocationRelativeTo(null);
        ImageIcon mainIcon = new ImageIcon("iconos/icono.png");
        setIconImage(mainIcon.getImage());
        setTitle("Gestor de Tarjetas");
    }

}
